version: '3.8'
services:
db:
image: mariadb:10.11
environment:
MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD:-root}'
MYSQL_DATABASE: '${DB_NAME:-app}'
MYSQL_USER: '${DB_USER:-app}'
MYSQL_PASSWORD: '${DB_PASSWORD:-app}'
volumes:
- db_data:/var/lib/mysql
ports:
- '3306:3306'
networks:
- app-network


php:
build:
context: ../backend
dockerfile: Dockerfile
volumes:
- ../backend:/srv/api:cached
- ../backend/vendor:/srv/api/vendor
- ../backend/public:/srv/api/public
environment:
DATABASE_URL: 'mysql://${DB_USER:-app}:${DB_PASSWORD:-app}@db:3306/${DB_NAME:-app}'
APP_ENV: dev
depends_on:
- db
networks:
- app-network


php-cli:
build:
context: ../backend
dockerfile: Dockerfile
entrypoint: ['php']
command: ['bin/console']
volumes:
- ../backend:/srv/api
networks:
- app-network


backend-nginx:
image: nginx:1.25-alpine
volumes:
- ../backend/public:/srv/api/public:ro
- ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
ports:
- '8000:80'
depends_on:
- php
networks:
- app-network


node-builder:
build:
context: ../frontend
dockerfile: Dockerfile
volumes:
- ../frontend:/usr/src/app:cached
command: ['npm', 'run', 'build']
networks:
- app-network


frontend-nginx:
image: nginx:1.25-alpine
volumes:
- ../frontend/dist:/usr/share/nginx/html:ro
- ../infra/frontend-nginx.conf:/etc/nginx/conf.d/default.conf:ro
ports:
- '4200:80'
depends_on:
- node-builder
networks:
- app-network


volumes:
db_data:


networks:
app-network:
driver: bridge

